import {chromium} from 'file:///F:/SINAL_RUIDO/entrelinhas-site/node_modules/playwright-core/index.mjs';import {spawn} from 'node:child_process';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const base=process.env.SR_QA_BASE||'http://127.0.0.1:4185';const local=!process.env.SR_QA_BASE||!!process.env.SR_QA_LOCAL;const server=!process.env.SR_QA_BASE?spawn(process.execPath,['node_modules/vite/bin/vite.js',...(process.env.SR_QA_DEV?[]:['preview']),'--host','127.0.0.1','--port','4185'],{windowsHide:true,stdio:'ignore'}):null;const results=[];
try {if(local)for(let i=0;i<120;i++){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,500));}
for(const channel of local?['chrome','msedge']:['chrome']){const browser=await chromium.launch({channel,headless:true});
for(const width of local?[320,393,768,1024,1440]:[393,1440])for(const path of ['/','/en/','/livros/sinal-ruido/','/en/signal-noise/','/livro/amostra/','/livro/sample/']){
const page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)failed.push(r.url());});await page.goto(base+path,{waitUntil:'networkidle',timeout:120000});
const layout=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,h1:document.querySelectorAll('h1').length,broken:[...document.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src)}));assert.ok(layout.scroll<=width+1,JSON.stringify({path,width,layout}));assert.equal(layout.h1,1);assert.equal(errors.length,0,JSON.stringify(errors));assert.equal(failed.length,0,JSON.stringify(failed));assert.equal(layout.broken.length,0);
if(path==='/'||path==='/en/'){assert.equal(await page.locator('.home-hero-book .btn--primary').count(),1);assert.equal(await page.locator('.home-hero-book .btn--outline').count(),1);assert.equal(await page.locator('.home-hero-book .btn--reading').count(),1);assert.equal(await page.locator('.home-hero-book .edition-indicators li').count(),3);assert.equal(await page.locator('.home-hero-book .conversion-meta,.hero-signal-line,.intro-overlay,.ambience-layer').count(),0);assert.equal(await page.locator('.sample-index li').count(),3);assert.equal(await page.locator('.dossier-labels li').count(),4);assert.equal(await page.locator('.home-vitrine .vitrine-card').count(),2);assert.equal(await page.locator('[data-transmission-line]').count(),3);
if(width<860){const pos=await page.locator('.home-hero-book__title,.home-hero-book__cover,.home-hero-book__pitch,.home-hero-book .conversion-actions').evaluateAll(els=>els.map(el=>({class:el.className,y:el.getBoundingClientRect().top})));const get=k=>pos.find(p=>p.class.includes(k)).y;assert.ok(get('__title')<get('__cover')&&get('__cover')<get('__pitch')&&get('__pitch')<get('conversion-actions'),JSON.stringify(pos));}
}
if(path.includes('/amostra/')||path.includes('/sample/')){await page.locator('[data-chapter-tab]').last().click();assert.equal(await page.locator('[data-reading-return]').isVisible(),true);assert.equal(await page.locator('[data-sample-finish] a:not([target])').count(),0);assert.equal(await page.locator('[data-sample-finish] a[target]').count(),2);const font=await page.locator('.reading-paper:not([hidden])').evaluate(el=>getComputedStyle(el).fontSize);await page.locator('[data-reading-size="up"]').click();await page.waitForTimeout(200);assert.notEqual(await page.locator('.reading-paper:not([hidden])').evaluate(el=>getComputedStyle(el).fontSize),font);}
if(width>=860){assert.equal(await page.locator('.main-nav > a,.main-nav > .nav-group > a').count(),5);}else{await page.locator('[data-mobile-nav-toggle]').click();assert.equal(await page.locator('[data-mobile-nav]').isVisible(),true);await page.locator('[data-mobile-nav-toggle]').click();}
assert.equal(await page.locator('[data-cmdk-open]').evaluate(el=>getComputedStyle(el,'::before').content),'none');await page.locator('[data-cmdk-open]').click();assert.equal(await page.locator('[data-cmdk-backdrop]').isVisible(),true);await page.keyboard.press('Escape');
if(channel==='chrome'&&[393,1440].includes(width)){await page.screenshot({path:`qa-conversion/editorial-${local?'local':'live'}-${width}-${path.replaceAll('/','_')}.png`});if(path==='/'||path==='/en/'){for(const cls of ['home-vitrine','home-catalog','author-compact']){await page.locator('.'+cls).scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.images].filter(i=>{const r=i.getBoundingClientRect();return r.top<innerHeight&&r.bottom>0&&r.left<innerWidth&&r.right>0&&r.width>0}).every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:`qa-conversion/editorial-${local?'local':'live'}-${width}-${path.replaceAll('/','_')}-${cls}.png`});}}}
results.push({channel,width,path,...layout,errors,failed});await page.close();}
await browser.close();}writeFileSync(`qa-conversion/editorial-${local?'results':'live-results'}.json`,JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({checks:results.length,passed:true}));}finally{server?.kill();}

